### ISSUE TITLE
Project creation with git repo error

### ISSUE THREAD

**Issue by Nabil-Lahssini** [devoteamgcloud/terraform-provider-looker#22]
Hello @pgw94. About your last commits, I just checked the project creation using the new method and I get a 500 error. I used the same method as shown in the example file, can you please check if it's an error on the example or on the code?

**Comment by pgw94** [comment]
Hello @Nabil-Lahssini. I will check and give feedback.

**Comment by pgw94** [comment]
@Nabil-Lahssini I tried to recreate error but in my environment this works correctly. But I noticed one thing in example. If we use git_username and git_password we want to authenticate by HTTPS, so the URL should also be a little different. In this example there is git@github.com:workspace/repo.git which is a correct reference for SSH authentication. For HTTPS authentication git_remote_url should be https://github.com/workspace/repo.git. Please confirm what kind of URL you have. If you have git_remote_url starts with git@githhub.... and change to https:/github.com... works I will update the documentation. If not, I will investigate this further.

**Comment by Nabil-Lahssini** [comment]
Thank you for your fast reply, indeed it was because I used the wrong URL. It works perfectly with the HTML URL. We can rather update the documentation or create an if-condition in the code to prevent this from happening. What do you think is best in this case? :)

**Comment by pgw94** [comment]
@Nabil-Lahssini I 've created Pull Request where I've updated the example file and added URL validator: https://github.com/devoteamgcloud/terraform-provider-looker/pull/23

**Comment by Nabil-Lahssini** [comment]
Awesome ! It's approved and merged.
