### ISSUE TITLE
Deploy Key

### ISSUE THREAD

**Issue by Baatof** [devoteamgcloud/terraform-provider-looker#28]
Hello, 

When I try to create a deploy_secret, terraform gives me an error 

Error: field: deploy_secret, code: invalid
│ 
│   with looker_project_git_repo.git_repo,
│   on adeo_team.tf line 183, in resource "looker_project_git_repo" "git_repo":
│  183:   deploy_secret = looker_project_git_deploy_key.git_key.public_key
│ 
│ Invalid deploy_secret. Cannot be longer than 128 characters

Any idea ?

Regards

**Comment by Nabil-Lahssini** [comment]
Hello,

You are trying to use the git deploy key into the "deploy_secret" variable which is used to authenticate requests to the webhook. Those are 2 totally different use cases.

Here is a setup where I create a github repository, generate a deploy key and link it to a Looker project -> [code sample.](https://gist.github.com/Nabil-Lahssini/75bc5557b5b4fb91d60e05eecc97a602) (Don't forget to setup the GitHub provider)

Regards,
Nabil Lahssini

**Comment by Baatof** [comment]
Hello Nabil, 

Thank you for your support.
In other terraform custom provider, the project_git_repo have the ability to take git_deploy_key in input and set it.

Is it possible to generate git_deploy_key as mentionned in your code and affect it to project_git_repo ?

**Comment by Baatof** [comment]
I find a solution ! Thank's

**Comment by Nabil-Lahssini** [comment]
The deploy key must be generated by Looker itself and set on the Github resource "github_repository_deploy_key" , since it uses SSH cloning method.
As far as I know, there is no other way of using the deploy key.
The other method is using HTTPS cloning and it requires username and API key.

I hope this answered your question.
