### ISSUE TITLE
Any plan to support looker user attributes?

### ISSUE THREAD

**Issue by rjminchuk** [devoteamgcloud/terraform-provider-looker#41]
I'm using looker user attributes in a multi-tenant way.. Any plan to support those resources in your provider?

**Comment by Nabil-Lahssini** [comment]
Hi @rjminchuk ,
Are you referring to the following resource? [link](https://developers.looker.com/api/explorer/4.0/methods/UserAttribute?sdk=py)

**Comment by Nabil-Lahssini** [comment]
@rjminchuk Release v0.2.8 has just been released and supports this resource. Thank you for your contribution ! :) 
I'll close this issue, don't hesitate to open a new one if you have more feedback.

**Comment by rjminchuk** [comment]
Wow! Quick turn around! Maybe you had this one in the barrel. Turns out, that we additionally need [User Attribute Group](https://developers.looker.com/api/explorer/4.0/methods/Group/update_user_attribute_group_value?sdk=ts&e=500). Not sure if you have another miracle up your sleeve or not, but I can open another issue for that. Thanks for the speedy turn around!
