### ISSUE TITLE
Manually deleted user cause next plan to error

### ISSUE THREAD

**Issue by JonasAmeye** [devoteamgcloud/terraform-provider-looker#47]
When someone manually deletes a user from Looker, the next plan will error with error code
`Error: GET https://REDACTED.cloud.looker.com/api/4.0/users/873: 404 The resource you're looking for could not be found`
This can afaik only be fixed by removing the user from the state. Wouldn't it make more sense that if a 404 is returned the provider marks it as having been deleted (same way the Google provider for example handles 404s). This is probably also the case for other resources.

**Comment by Nabil-Lahssini** [comment]
Which version of the looker provider is used to perform this action?

**Comment by JonasAmeye** [comment]
Nevermind, I'm silly and didn't check the version, thanks for replying!
