### ISSUE TITLE
Add "looker_user_attribute" to supported data sources

### ISSUE THREAD

**Issue by daniel-meireles** [devoteamgcloud/terraform-provider-looker#60]
We are trying to add the landing_page built-in user attribute to terraform as a data source, but apparently you are not supporting that at the moment. Could you please add that? Thanks.

The provider devoteamgcloud/looker does not support data source
"looker_user_attribute"

**Comment by daniel-meireles** [comment]
@Nabil-Lahssini

**Comment by Nabil-Lahssini** [comment]
Hi,
The user attribute data source is now supported. v0.2.18 comes with these changes.
Thank you for your contribution and sorry for the delay !

**Comment by daniel-meireles** [comment]
Thanks! @Nabil-Lahssini
