### ISSUE TITLE
data resource for public IPs

### ISSUE THREAD

**Issue by Symbianx** [devoteamgcloud/terraform-provider-looker#66]
Hello 👋 

Would be nice to have a data resource to get the Public IP Addresses of the looker instance.

We're implementing looker -> snowflake connections and need a network policy on the snowflake side in order for looker to connect. Currently, there's no way to programatically get this with terraform so we had to hard code the Public IP Addresses in the snowflake network policy terraform code.

Something like this would be great:
```terraform
data "looker_public_ip_addresses" "current" {}
```

**Comment by Nabil-Lahssini** [comment]
Hello @Symbianx,
Thank you for your contribution. You can find this exact data source in the new release **v0.3.2**. It is very simple to use. Please refer to the [documentation](https://registry.terraform.io/providers/devoteamgcloud/looker/latest/docs/data-sources/public_ip_addresses) for this.
Hope it helps,
Nabil Lahssini
