### ISSUE TITLE
Adding "Theme" resource

### ISSUE THREAD

**Issue by Nabil-Lahssini** [devoteamgcloud/terraform-provider-looker#7]
Adding the support for the Theme resource. 
This includes:
- The "Theme" object at "/pkg/lookergo" 
- Standard CRUD in the resources folder "/internal/provider".
- Add your resource to the ResourcesMap at "/internal/provider/provider.go:67"

[**Looker official Theme API documentation**](https://developers.looker.com/api/explorer/4.0/methods/Theme?sdk=go)

**Comment by jcvegan** [comment]
@Nabil-Lahssini is ther a plan to support this feature?

**Comment by Nabil-Lahssini** [comment]
Hey @jcvegan , I have worked on this issue and the code is ready. The problem is that I don't have a Looker instance with a licence for Themes to test it before deploying it.

**Comment by jcvegan** [comment]
@Nabil-Lahssini is it possible toshare your branch so I can tes it on my end?

**Comment by jjureta-ueat** [comment]
@Nabil-Lahssini I've tried to use a theme resource:
```
resource "looker_theme" "my_theme" {
  # begin_at = "2023‐01‐01T00:00:00Z"
  # begin_at = null
  name = "My theme name"
  settings {
    background_color = "#ffffff"
    font_color = "#000000"
    show_filters_bar = false
    show_title = true
  }
}
```

but I'm getting an error:
```
Error: begin_at: '' expected type 'string', got unconvertible type 'time.Time', value: '0001-01-01 00:00:00 +0000 +0000'
│
│   with looker_theme.my_theme,
│   on looker-themes.tf line 1, in resource "looker_theme" "my_theme":
│    1: resource "looker_theme" "my_theme" {
``` 

I've tried to put different strings as a value of `begin_at`, but I'm getting always the same error.
Any idea what is wrong? Can you share an exemple how a theme should be defined?

**Comment by Nabil-Lahssini** [comment]
Hi @jcvegan @jjureta-ueat ,
Thanks for helping ! v0.4.0 supports this feature. Please refer to [the documentation](https://registry.terraform.io/providers/devoteamgcloud/looker/latest/docs/resources/theme) for further explanation :) 

Kind regards,
Nabil Lahssini
