### ISSUE TITLE
User attribute member only supports a single group/value

### ISSUE THREAD

**Issue by brianteagueuvabs** [devoteamgcloud/terraform-provider-looker#77]
User attribute members only support a single group value. When trying to add multiple group values to an attribute, the 2nd group value replaces the first group value instead of being added alongside it. Looker supports having multiple group values attached to an attribute, so I'm not sure whether this behavior by the provider is intentional or not.

**Comment by Nabil-Lahssini** [comment]
Hi @brianteagueuvabs,

I tried reproducing the situation you just described and adding multiple groups to a single looker_user_attribute_member resource block is working fine.
Make sure to use the latest version of the provider. If the error still persists, please provide me with the terraform code sample you are using.

Thank you for reaching out !
Nabil Lahssini

**Comment by brianteagueuvabs** [comment]
Hey @Nabil-Lahssini, we're creating these dynamically with HCL, so given a yaml file that looks like this
```
internal:
  groups:
    group1:
      user_attribute: attribute_a
      value: value-a
    group2:
      user_attribute: attribute_b
      value: value-b
```
this is the code block for Terraform:
```
resource "looker_user_attribute_member" "internal" {

  for_each = {
    for item in flatten([
      for file in local.files.all : [
        for group, config in yamldecode(
          file(
            "${local.path.full}/${file}"
          )
          ).internal.groups : {
          file           = file
          group          = group
          user_attribute = config.user_attribute
          value          = config.value
        }
      ]
    ])
    : "${item.file}_${item.group}" => item if item.group != null
  }

  user_attribute_id = looker_user_attribute.user_attribute[each.value.user_attribute].id

  group {
    id = looker_group.internal[each.key].id
    value = each.value.value
  }
}
```

Basically what's happening is that the plan shows the expected output, which is adding 2 groups to whichever user attribute. During the apply, however, it looks like this:
1. First object (group) in queue gets applied
2. Second object (group) in queue gets applied, replacing the first object

This leaves the user attribute with a single group applied. The next plan will show the first group still needing to be added, and once it applies it replaces the existing (second) group. Each successive plan/apply alternates which group it will apply, never applying both.

I'm using similar code for role groups, and even though I had to run the plan/apply twice to get both groups assigned to a single role, it still applied both of them.

We are using v**0.3.5** of the provider.

Please let me know if there's any other information I can provide. I appreciate you looking into it.

**Comment by Nabil-Lahssini** [comment]
Hi @brianteagueuvabs,
The problem you are describing is a terraform syntax problem. When looking at the code you provided, you are only adding one group to each resource.
If you want to programmatically add multiple groups, check the following [resource](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks#:~:text=You%20can%20dynamically%20construct%20repeatable%20nested%20blocks%20like%20setting%20using%20a%20special%20dynamic%20block%20type%2C%20which%20is%20supported%20inside%20resource%2C%20data%2C%20provider%2C%20and%20provisioner%20blocks%3A)
To be sure that the issue is  a syntax issue, please try applying following code:
```
resource "looker_user_attribute" "att" {
  name = "attribute_name"
  label = "attribute label"
  type = "string"
}

resource "looker_group" "my-group" {
  name = "mygroup"
}

resource "looker_group" "my-groupp" {
  name = "mygroup2"
}

resource "looker_user_attribute_member" "name" {
  user_attribute_id = looker_user_attribute.att.id
  group {
    id = looker_group.my-group.id
    value = "attribute-value"
  }
  group {
    id = looker_group.my-groupp.id
    value = "attribute-value"
  }
}
```
If the user attribute gets 2 groups assigned successfully,  the issue isn't from the provider.

Hope it helps !
